"""add missing mistake_rule_definitions and any other drifted tables

Revision ID: f3ade05828f8
Revises: fead6f0f4306
Create Date: 2026-09-14 08:19:54.943748

Hand-trimmed from the raw autogenerate output (same discipline
88895bef5a38's own docstring already documents): 4 ORM models
(MistakeRuleDefinition, SignalContextSnapshot, TradeIntent, TradeTag) had
apparently NEVER had a migration generated for them at all -- confirmed by
grep, none appear in any prior alembic/versions/*.py or in
deployment/docker/init.sql. Only surfaced now because this is, as far as
this session found, the first time this project's Postgres has ever been
rebuilt from a genuinely empty volume (the running dev database had
presumably carried these tables since whenever they were first added,
via some untracked one-off `Base.metadata.create_all()` or manual DDL,
never captured as a migration). Removed from the raw autogenerate diff:
the repeat of the already-known "replace the superior 3-column ohlcv
composite index with a worse single-column one" issue 88895bef5a38's own
docstring already names -- same real, pre-existing, out-of-scope drift,
not something this migration should touch.
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'f3ade05828f8'
down_revision: Union[str, Sequence[str], None] = 'fead6f0f4306'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('mistake_rule_definitions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('rule_key', sa.String(length=64), nullable=False),
    sa.Column('label', sa.String(length=200), nullable=False),
    sa.Column('category', sa.String(length=30), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('params', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('rule_key')
    )
    op.create_table('signal_context_snapshots',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('signal_id', sa.BigInteger(), nullable=False),
    sa.Column('killzone_active', sa.Boolean(), nullable=False),
    sa.Column('active_killzones', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('captured_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['signal_id'], ['signals.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_signal_context_snapshots_signal_id'), 'signal_context_snapshots', ['signal_id'], unique=True)
    op.create_table('trade_intents',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('signal_id', sa.BigInteger(), nullable=True),
    sa.Column('symbol', sa.String(length=20), nullable=False),
    sa.Column('direction', sa.String(length=10), nullable=False),
    sa.Column('intended_entry_price', sa.Numeric(precision=18, scale=6), nullable=True),
    sa.Column('marked_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['signal_id'], ['signals.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_trade_intents_signal_id'), 'trade_intents', ['signal_id'], unique=False)
    op.create_index(op.f('ix_trade_intents_symbol'), 'trade_intents', ['symbol'], unique=False)
    op.create_table('trade_tags',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('trade_id', sa.BigInteger(), nullable=False),
    sa.Column('category', sa.String(length=30), nullable=False),
    sa.Column('tag_key', sa.String(length=64), nullable=False),
    sa.Column('negative', sa.Boolean(), nullable=False),
    sa.Column('detail', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['trade_id'], ['trades.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_trade_tags_tag_key'), 'trade_tags', ['tag_key'], unique=False)
    op.create_index(op.f('ix_trade_tags_trade_id'), 'trade_tags', ['trade_id'], unique=False)
    # ### end Alembic commands ### (ohlcv index churn removed -- see module docstring)


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ### (ohlcv index churn removed -- see module docstring)
    op.drop_index(op.f('ix_trade_tags_trade_id'), table_name='trade_tags')
    op.drop_index(op.f('ix_trade_tags_tag_key'), table_name='trade_tags')
    op.drop_table('trade_tags')
    op.drop_index(op.f('ix_trade_intents_symbol'), table_name='trade_intents')
    op.drop_index(op.f('ix_trade_intents_signal_id'), table_name='trade_intents')
    op.drop_table('trade_intents')
    op.drop_index(op.f('ix_signal_context_snapshots_signal_id'), table_name='signal_context_snapshots')
    op.drop_table('signal_context_snapshots')
    op.drop_table('mistake_rule_definitions')
    # ### end Alembic commands ###
