"""Generate one model card per live strategy override.

Both PDFs read from data/PDF/ on 2026-09-13 (the meta-labeling and solo-
quant validation advisories) list model cards / a decision journal among
their cheap-but-secondary governance practices. Direct verification found
this platform already has the SUBSTANCE of a model card scattered across
two places for every override: the override JSON itself
(data/models/e51_signals/*_strategy_override.json -- params, validated_at,
source, win_rate, IS/OOS Sharpe, drawdown, trade count, and since Stage 0
a full `stage0` block with verdict/DSR/null-percentile/caveats) and
CLAUDE.md's own dated, append-only decision log. What was missing was a
single human-readable artifact PER MODEL -- this script assembles one
from data that already exists, fabricating nothing.

Auto-generated output, not hand-edited: rerun this script to refresh
docs/model_cards/ any time override files change (Stage 0 re-tagging, a
fresh promotion, a withdrawal). A card that looks stale relative to the
override JSON's own `validated_at`/`stage0.evaluated_at` timestamps means
this script needs rerunning, not that the card should be hand-patched.

Usage: python scripts/generate_model_cards.py
"""
import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
OVERRIDE_DIR = ROOT / "data" / "models" / "e51_signals"
OUTPUT_DIR = ROOT / "docs" / "model_cards"


def _fmt_params(params: dict) -> str:
    if not params:
        return "(none)"
    return ", ".join(f"`{k}={v}`" for k, v in params.items())


def _stage0_section(stage0: dict | None) -> str:
    if not stage0:
        return (
            "**No Stage 0 tag present.** Per `engines/e51_signals/engine.py`'s "
            "deny-by-default rule (docs/STAGE0_FINDINGS.md), a missing tag now "
            "means this override does NOT fire live -- it is treated the same "
            "as `UNVALIDATED`, not as pre-Stage0 `active`."
        )
    status = stage0.get("status", "UNKNOWN")
    measured = stage0.get("measured", {})
    lines = [
        f"**Status: {status}**",
        "",
        f"- Evaluated: {stage0.get('evaluated_at', 'n/a')}",
        f"- Selection score (min IS/OOS): {measured.get('selection_score', 'n/a')} "
        f"(bar: {stage0.get('bar', {}).get('min_null_percentile', 'n/a')}th null percentile, "
        f"{stage0.get('bar', {}).get('min_trades', 'n/a')} min trades)",
        f"- Null percentile: {measured.get('null_percentile', 'n/a')} "
        f"(source: {measured.get('null_source', 'n/a')}"
        f"{', CROSS-ASSET PROXY' if measured.get('null_is_proxy') else ''})",
        f"- Trades measured: {measured.get('trades', 'n/a')}, "
        f"N_effective: {measured.get('n_effective', 'n/a')}",
        f"- DSR (reported diagnostic, NOT a gate -- see docs/STAGE0_FINDINGS.md"
        f" section 4): {stage0.get('dsr_diagnostic', 'n/a')}",
    ]
    reasons = stage0.get("reasons") or []
    if reasons:
        lines.append(f"- Rejection reasons: {'; '.join(reasons)}")
    caveats = stage0.get("caveats") or []
    if caveats:
        lines.append("- Caveats:")
        lines.extend(f"  - {c}" for c in caveats)
    return "\n".join(lines)


def _card_markdown(symbol_tf: str, d: dict) -> str:
    retired_at = d.get("retired_at")
    retired_note = (
        f"\n> **RETIRED at {retired_at}.** This override no longer fires "
        f"regardless of Stage 0 status -- see `engines/e51_signals/engine.py`'s "
        f"`retired_at` tombstone check.\n"
        if retired_at else ""
    )
    return f"""# Model Card: {symbol_tf}
{retired_note}
Auto-generated by `scripts/generate_model_cards.py` from
`data/models/e51_signals/{symbol_tf}_strategy_override.json`. Do not hand-edit --
rerun the script instead.

## Model details

- **Strategy**: `{d.get('strategy', 'n/a')}`
- **Parameters**: {_fmt_params(d.get('params', {}))}
- **Symbol / timeframe**: {symbol_tf}
- **Source**: {d.get('source', 'n/a')}
- **Validated at**: {d.get('validated_at', 'n/a')}

## Intended use

Directional strategy override for `engines/e51_signals` on this symbol/
timeframe only. Falls back to the baseline composite rule if Stage 0
status is anything other than `VALIDATED`, or if `retired_at` is set
(see Stage 0 section below) -- this is a reversible, data-driven gate,
not a code path that must be edited to disable a bad override.

## Training / validation performance (E24 -> E26 walk-forward)

| metric | value |
|---|---|
| Win rate | {d.get('win_rate', 'n/a')} |
| IS Sharpe | {d.get('is_sharpe', 'n/a')} |
| OOS Sharpe | {d.get('oos_sharpe', 'n/a')} |
| Max drawdown | {d.get('max_drawdown_pct', 'n/a')}% |
| Total trades | {d.get('total_trades', 'n/a')} |
| Min confidence gate | {d.get('min_confidence', 'n/a')} |

{d.get('note', '')}

## Stage 0 validation (docs/STAGE0_FINDINGS.md)

{_stage0_section(d.get('stage0'))}

## Known limitations

- IS/OOS Sharpe here assumes near-IID returns; Stage 0's own DSR diagnostic
  is a ceiling, not an estimate, due to uncorrected serial dependence
  (docs/STAGE0_FINDINGS.md caveat 3).
- The null this override was scored against may be a cross-asset proxy
  (gold, GC=F) rather than this asset's own null -- see the Stage 0
  section above for whether that applies here.
- This card reflects the override file's state at generation time. A
  known live risk (documented in CLAUDE.md's 2026-09-12 Phase 7 section):
  independent, uncoordinated scripts can overwrite override files and
  silently strip their Stage 0 tag. Re-run `scripts/apply_stage0_tags.py`
  and this generator if the override JSON's own timestamps look newer
  than expected.
"""


def main() -> None:
    OUTPUT_DIR.mkdir(parents=True, exist_ok=True)
    override_files = sorted(OVERRIDE_DIR.glob("*_strategy_override.json"))
    written = []
    for path in override_files:
        symbol_tf = path.name.removesuffix("_strategy_override.json")
        data = json.loads(path.read_text())
        card = _card_markdown(symbol_tf, data)
        out_path = OUTPUT_DIR / f"{symbol_tf}.md"
        out_path.write_text(card, encoding="utf-8")
        written.append(out_path)

    index_lines = [
        "# Model Cards",
        "",
        "Auto-generated by `scripts/generate_model_cards.py` from every live"
        " strategy override in `data/models/e51_signals/`. Rerun the script to"
        " refresh after any Stage 0 re-tagging, promotion, or retirement -- do"
        " not hand-edit individual cards.",
        "",
        f"{len(written)} overrides, generated from `data/models/e51_signals/*_strategy_override.json`.",
        "",
        "| symbol/timeframe | strategy | stage0 status |",
        "|---|---|---|",
    ]
    for path in written:
        symbol_tf = path.stem
        data = json.loads((OVERRIDE_DIR / f"{symbol_tf}_strategy_override.json").read_text())
        status = (data.get("stage0") or {}).get("status", "NO TAG")
        if data.get("retired_at"):
            status = f"RETIRED ({status})"
        index_lines.append(f"| [{symbol_tf}]({symbol_tf}.md) | `{data.get('strategy', 'n/a')}` | {status} |")

    (OUTPUT_DIR / "README.md").write_text("\n".join(index_lines) + "\n", encoding="utf-8")
    print(f"wrote {len(written)} model cards + README.md to {OUTPUT_DIR}")


if __name__ == "__main__":
    main()
