"""Engine 31 -- Portfolio Construction."""

from project_titan_x.engines.e31_portfolio_construction.engine import (
    BlackLittermanResult,
    EfficientFrontierResult,
    HierarchicalRiskParityResult,
    PortfolioConstructionEngine,
    RiskParityResult,
    VolatilityTargetResult,
    WeightsResult,
    black_litterman_posterior,
    covariance_matrix_from_returns,
    efficient_frontier,
    hierarchical_risk_parity_weights,
    implied_equilibrium_returns,
    leverage_for_target_vol,
    max_sharpe_weights,
    min_variance_weights,
    portfolio_return,
    portfolio_volatility,
    risk_contributions,
    risk_parity_weights,
    scale_weights_to_target_vol,
)

__all__ = [
    "BlackLittermanResult",
    "EfficientFrontierResult",
    "HierarchicalRiskParityResult",
    "PortfolioConstructionEngine",
    "RiskParityResult",
    "VolatilityTargetResult",
    "WeightsResult",
    "black_litterman_posterior",
    "covariance_matrix_from_returns",
    "efficient_frontier",
    "hierarchical_risk_parity_weights",
    "implied_equilibrium_returns",
    "leverage_for_target_vol",
    "max_sharpe_weights",
    "min_variance_weights",
    "portfolio_return",
    "portfolio_volatility",
    "risk_contributions",
    "risk_parity_weights",
    "scale_weights_to_target_vol",
]
